### ISSUE TITLE
BUG: namedGroup not determined correctly

### ISSUE THREAD

**Issue by cawa-93** [WP-API/node-wpapi#350]
https://github.com/WP-API/node-wpapi/blob/7427d6fbee11cc0f20d5b977c75ff927a2c49dbf/lib/route-tree.js#L36
```js
// component == (?P<post_ids>([a-zA-Z0-9_]\,?)+)
var namedGroup = component.match( namedGroupRE );
/*
 [ '(?P<post_ids>([a-zA-Z0-9_]\\,?)', 
  'post_ids',
  '([a-zA-Z0-9_]\\,?', <-- ERROR in RegExp: Unterminated group
  index: 0,
  input: '(?P<post_ids>([a-zA-Z0-9_]\\,?)+)' ]
*/
```

https://github.com/WP-API/node-wpapi/blob/7427d6fbee11cc0f20d5b977c75ff927a2c49dbf/lib/route-tree.js#L83

```js
SyntaxError: Invalid regular expression: /^([a-zA-Z0-9_]\,?$/: Unterminated group
    at new RegExp (<anonymous>)
    at reduceRouteComponents (D:\Develop\parser\node_modules\wpapi\lib\route-tree.js:93:3)
    at Array.reduce (<anonymous>)
    at reduceRouteTree (D:\Develop\parser\node_modules\wpapi\lib\route-tree.js:193:18)
    at D:\Develop\parser\node_modules\wpapi\lib\util\object-reduce.js:24:10
    at Array.reduce (<anonymous>)
    at module.exports (D:\Develop\parser\node_modules\wpapi\lib\util\object-reduce.js:23:28)
    at buildRouteTree (D:\Develop\parser\node_modules\wpapi\lib\route-tree.js:208:9)
    at WPAPI.bootstrap (D:\Develop\parser\node_modules\wpapi\wpapi.js:348:23)
    at new WPAPI (D:\Develop\parser\node_modules\wpapi\wpapi.js:89:4)
    at D:\Develop\parser\node_modules\wpapi\wpapi.js:447:11
    at tryCatch (D:\Develop\parser\node_modules\es6-promise\dist\es6-promise.js:410:12)
    at invokeCallback (D:\Develop\parser\node_modules\es6-promise\dist\es6-promise.js:425:13)
    at publish (D:\Develop\parser\node_modules\es6-promise\dist\es6-promise.js:393:7)
    at flush (D:\Develop\parser\node_modules\es6-promise\dist\es6-promise.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by kadamwhite** [comment]
@cawa-93 Thanks for the issue report. I'm not sure how to interpret the ticket, I'm afraid. There is no invalid regular expression within this library's code --- I assume from your description that you have a plugin which supplies a route which is parsed into an incorrect regular expression?

If you can share the route string which is causing this issue, I'll see whether I can identify the shortcoming in our logic. Thanks!

**Comment by kadamwhite** [comment]
I'm going to close this due to lack of response; I do not currently have enough information to replicate or debug the issue. If you continue to experience this bug, please add a comment or open a new issue to keep the conversation going. Thank you for your bug report, and for using the library!

**Comment by sebakerckhof** [comment]
Workaround in wordpress:
```php
add_filter( 'rest_endpoints', 'remove_default_endpoints_smarter' );
  
function remove_default_endpoints_smarter( $endpoints ) {
	//  workaround for npm wpapi bug
  foreach ( $endpoints as $endpoint => $details ) {
		if (strpos($endpoint, 'plugins') !== false) {
			unset( $endpoints[$endpoint] );
		}
  }
 
  return $endpoints;
}
```

**Comment by Triloworld** [comment]
Pleas reopen - find that bug. Fix from @sebakerckhof  help but that disable route and don't fix new patterns like "(?:<pattern>)" as @SamiSousa mention
