### ISSUE TITLE
Gateway Timeout

### ISSUE THREAD

**Issue by tleite** [WP-API/node-wpapi#363]
- Is there a limit on how many requests per second?
- I'm looping through a list and deleting posts
- I've already added a delay of 500ms per call, but I still get this timeout error once in a while, any suggestions?

Error: Gateway Timeout
    at Request.callback (/node_modules/superagent/lib/node/index.js:706:15)
    at IncomingMessage.parser (/node_modules/superagent/lib/node/index.js:916:18)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by kadamwhite** [comment]
Not sure I can answer without knowing more about your server configuration; there's not a formal limit within the REST API, but it's definitely possible to overwhelm your server if you make too many complex requests. The best approach would be to add logic to your app to retry requests with exponential backoff in the event of a timeout.
