### ISSUE TITLE
Getting Error: Cannot find module 'wpapi/superagent'

### ISSUE THREAD

**Issue by murshid1988** [WP-API/node-wpapi#451]
```
Require stack:
- /home/murshid/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/murshid/server.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/murshid/server.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myna-election-result@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myna-election-result@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by iabbaskhan** [comment]
Make sure you have installed superagent ```npm i --save superagent``` - then require WPAPI like this:

```var WPAPI = require("wpapi");``` without ```/superagent``` - this worked for me. Also make sure you've installed the Basic Auth plugin on your WordPress website before making any requests (if you're using username:password auth).
